DM-813: Add Agent fragment to the device-capability-model
Cumulocity-IoT/cumulocity-clients-java pull request #120
Opened 2022-05-11 19:39 UTC by georgi-huklev

2022-05-12 07:21 UTC, georgi-huklev commented
There are a lot of random files that github thinks have changed. That is because I squash merged from develop and because of the silly diff algorithm github is using(see [kirkwatrous](https://github.community/u/kirkwatrous)'s comment [here](https://github.community/t/github-pull-requests-showing-invalid-diff-for-already-merged-branch/559)). 

[This](https://github.com/SoftwareAG/cumulocity-clients-java/compare/develop..DM-813-bd-as-device-integrator-i-want-to-set-the-agent-fragment-using-a-sr2-static-templates) is the actual diff.

2022-05-13 15:25 UTC, l2p- approved these changes, later dismissed

2022-05-16 12:20 UTC, MaciekSoftwareAG requested changes

2022-05-16 12:20 UTC, MaciekSoftwareAG commented on device-capability-model/src/main/java/c8y/Agent.java
> +public class Agent extends AbstractDynamicProperties {
javadoc please

2022-05-16 14:51 UTC, l2p- approved these changes, later dismissed

2022-05-17 15:43 UTC, MaciekSoftwareAG approved these changes

2022-05-19 08:48 UTC, l2p- approved these changes

2022-05-19 09:19 UTC, merged