IPG-314 merge develop_cicd (new CI/CD) changes to relevant branches
Cumulocity-IoT/cumulocity-clients-java pull request #17
Opened 2021-10-27 09:55 UTC by zocimek

2021-10-27 10:03 UTC, ghost submitted a review, later dismissed
The bitbucket debug changes could be skipped...

2021-10-27 10:19 UTC, ghost requested changes

2021-10-27 10:19 UTC, ghost commented on lpwan-backend/pom.xml
> +        <revision>1.206.0</revision>
Is this required?

2021-10-27 10:19 UTC, ghost commented on README.md
> +These tools are provided as-is and without warranty or support. They do not constitute part of the Software AG product suite. Users are free to use, fork and modify them, subject to the license agree
This should be removed, cumulocity-clients-java is not a fan project

2021-10-27 11:05 UTC, d-mariak commented on .jenkins/scripts/test.sh
> +# MVN_EXEC="$(pwd)/mvnw"
Do we need commented code?

2021-10-27 11:10 UTC, d-mariak commented on .jenkins/bitbucket/sdk_test.jenkinsfile
> +import groovy.json.*
Same changes should be provided to sdk_test.jenkinsfile in github package?

2021-10-27 15:15 UTC, ghost submitted a review, later dismissed

2021-10-27 15:15 UTC, ghost commented on .jenkins/bitbucket/sdk_test.jenkinsfile
> +import groovy.json.*
Yeah I think that this is just not needed, as this is some test stuff. Probably shouldn't be in PR at all.

2021-10-27 16:11 UTC, c8y-kh4mell commented on README.md
> +These tools are provided as-is and without warranty or support. They do not constitute part of the Software AG product suite. Users are free to use, fork and modify them, subject to the license agree
remove

2021-10-27 16:12 UTC, c8y-kh4mell commented on microservice/pom.xml
> -    <scm>
why removed?

2021-10-27 16:13 UTC, c8y-kh4mell commented on .jenkins/scripts/common.sh
> -export release_args="-DskipTests -Dmaven.javadoc.skip=true -Dskip.microservice.package=false -Dskip.agent.package.container=false -Dnexus.url=http://nexus:8081  -Darguments=-Dskip.microservice.packag
why nexus.url removed?

2021-10-27 16:15 UTC, c8y-kh4mell submitted a review, later dismissed

2021-10-28 10:45 UTC, c8y-kh4mell approved these changes

2021-10-28 10:45 UTC, ghost approved these changes

2021-10-28 13:56 UTC, merged