MTM-53019 add image pull secret for sdk package plugin
Cumulocity-IoT/cumulocity-clients-java pull request #324
Opened 2023-04-21 11:45 UTC by AleksanderFiszSoftwareag

2023-04-21 11:49 UTC, kaczynskid-sag reviewed
Isn't the registry part of the `package.docker.baseImage` already?
Can't this credentials be configured in local docker deamon instad?

2023-04-21 11:49 UTC, kaczynskid-sag commented on microservice/package/src/main/java/com/cumulocity/agent/packaging/BaseMicroserviceMojo.java
> +    protected String pullPassword;
use the same prefix as `package.docker.baseImage`
```suggestion
    @Parameter(property = "package.docker.registry")
    protected String pullRegistry;

    @Parameter(property = "package.docker.username")
    protected String pullUsername;

    @Parameter(property = "package.docker.password")
    protected String pullPassword;
```

2023-04-21 11:52 UTC, pawelkowalczyksag submitted a review, later dismissed

2023-04-21 11:56 UTC, c8y-kh4mell submitted a review, later dismissed

2023-04-21 12:28 UTC, pawelkowalczyksag submitted a review, later dismissed

2023-04-21 12:47 UTC, pawelkowalczyksag approved these changes, later dismissed

2023-04-21 13:46 UTC, karolkaczmarski-sag approved these changes, later dismissed

2023-04-24 07:15 UTC, c8y-kh4mell submitted a review, later dismissed

2023-04-24 07:15 UTC, c8y-kh4mell commented on microservice/package/src/main/java/com/cumulocity/agent/packaging/microservice/impl/MicroserviceDockerClientImpl.java
> +    synchronized public void buildDockerImage(String dockerDirectory, Set<String> tags, Map<String, String> buildArgs, String platform, String networkMode, Integer dockerBuildTimeout, AuthConfigurati
trivial
```suggestion
    synchronized public void buildDockerImage(String dockerDirectory, Set<String> tags, Map<String, String> buildArgs, String platform, String networkMode, Integer dockerBuildTimeout, AuthConfigurations pullConfiguration) {
```

2023-04-24 07:15 UTC, c8y-kh4mell commented on microservice/package/src/test/java/com/cumulocity/agent/packaging/PackageMojoTest.java
> +    public void pullRegistryShouldBeCalculatedBaseImageIfEmpty(){
```suggestion
    public void pullRegistryShouldCalculateBaseImageIfEmpty(){
```

2023-04-24 07:41 UTC, c8y-kh4mell submitted a review, later dismissed

2023-04-24 07:50 UTC, jkot-softwareag approved these changes, later dismissed

2023-04-24 07:50 UTC, jkot-softwareag commented on microservice/package/src/main/java/com/cumulocity/agent/packaging/PackageMojo.java
> +        if(isNotBlank(pullUsername) && isNotBlank(pullPassword)){
minor: maybe log.info() with some details in this IF branch?

2023-04-24 08:26 UTC, jkot-softwareag submitted a review, later dismissed

2023-04-24 10:48 UTC, karolkaczmarski-sag submitted a review, later dismissed

2023-04-24 11:28 UTC, kaczynskid-sag requested changes

2023-04-24 11:28 UTC, kaczynskid-sag commented on microservice/package/src/main/java/com/cumulocity/agent/packaging/PackageMojo.java
> +            }
Should correspond to existing available settings

2023-04-24 11:28 UTC, kaczynskid-sag commented on microservice/package/src/main/java/com/cumulocity/agent/packaging/PackageMojo.java
> +            return baseImage.contains("/") ? baseImage.substring(0, baseImage.lastIndexOf("/")) : null;
default is docker-hub, not null

2023-04-24 11:58 UTC, kaczynskid-sag approved these changes

2023-04-25 13:59 UTC, karolkaczmarski-sag approved these changes

2023-04-26 13:05 UTC, merged