MTM-44093 mqtt token refresh (Generic MQTT)
Cumulocity-IoT/cumulocity-clients-java pull request #74
Opened 2022-03-09 14:46 UTC by andrekramer1

2022-03-25 15:51 UTC, gapa-c8y requested changes
Might be mixing up params in my head, so either correct me or the PR!

2022-03-25 15:51 UTC, gapa-c8y commented on java-client/src/test/java/com/cumulocity/sdk/client/messaging/notifications/TokenApiImplTest.java
> +                new NotificationTokenRequestRepresentation(null, "sub", "sup", true, 1L, false);
I might be getting mixed up, but should the null value be 3rd (type) parameter here?

2022-03-25 15:51 UTC, gapa-c8y commented on java-client/src/test/java/com/cumulocity/sdk/client/messaging/notifications/TokenApiImplTest.java
> +                new NotificationTokenRequestRepresentation(null, "sub", "sup", true, 1L, false);
Same here (should null be 3rd param)

2022-03-25 16:11 UTC, andrekramer1 commented on java-client/src/test/java/com/cumulocity/sdk/client/messaging/notifications/TokenApiImplTest.java
> +                new NotificationTokenRequestRepresentation(null, "sub", "sup", true, 1L, false);
Good spot! thanks.

2022-03-25 16:41 UTC, gapa-c8y approved these changes, later dismissed

2022-03-28 07:50 UTC, rohitjoshi-softwareag submitted a review, later dismissed

2022-08-02 07:00 UTC, rohitjoshi-softwareag approved these changes

2022-08-02 08:53 UTC, gapa-c8y approved these changes

2022-08-02 16:00 UTC, bggov approved these changes

2022-08-03 00:34 UTC, merged